### ISSUE TITLE
Add hooks

### ISSUE THREAD

**Issue by pebly** [UnexomWid/eryn#30]
It would be nice if users would can to pre/post process data on compile/render time.

The concept:
```
files --(content)--> hook --(modified content)--> run eryn as usual using the modified content
```

Suggested syntax:

```javascript
eryn.setHook('preCompiler', (path, content) => {
  // do whatever with file path or the content
  return content;
});
```

**Comment by UnexomWid** [comment]
Pre-render hooks can actually be invoked at compile-time, because the content itself is a file and doesn't depend on the state (`context` and `local`).

Post-render hooks are a bit more complicated, because the content isn't file content anymore; it's **rendered** content. Therefore, it has to happen at render-time. This adds some complexity to the renderer, as it currently writes directly to the output buffer. If post-render hooks are present, the renderer has to pass the content to the hook via the bridge, and then it has to overwrite the previously-rendered content, while also readjusting the buffer size accordingly.

Also, hooks should correspond to a single **eryn** instance, in order to avoid unwanted hook invocation in other modules. Currently, there is no support for multiple **eryn** instances (as there is a single, global instance, which isn't ideal).

Since post-render hooks may have a non-negligible impact on the renderer performance, and since multiple **eryn** instances are not supported yet (but are planned to be), hooks will be introduced in a later release, such as `0.3` or `0.4`.
