### ISSUE TITLE
Support for async function calls inside Eryn's templates

### ISSUE THREAD

**Issue by pebly** [UnexomWid/eryn#36]
It would be nice to have the ability to call an async function directly in the templates, by detecting `await` keyword. Eryn would call the context function and wait for the Promise to be resolved.
```javascript
[|? await context.connected()  |]
  Welcome back, [| await context.user() |]
[|:|]
  Sign in to continue
[|end|]
```

Another, more simple solution (I think), would allow developers to store into `local` variables values returned from async functions by using the new Async Template.

###### Note: The current solution for this problem is creating an async wrapper in Node.js, and render eryn files with resolved data from Promises.

**Comment by UnexomWid** [comment]
One possible solution would be to add another template type. When rendering that template, the renderer would need to create a new buffer containing the code, wrapped around `await (async () => { code })()`. This would then be passed to the bridge eval function.

Actually, there is no need to do that during rendering. The wrapper can be written during compilation, because it doesn't depend on the state.

The problem with implementing a new template type is that other templates (such as loops and conditionals) will not have access to this. It will be something specific to that template type. Therefore, I propose adding a new marker that can be used in most templates. Something like `async`, or `&` for short:

```js
[|?& context.connected() |]
    Welcome back, [|& context.user() |]
[|:|]
    Sign in to continue
[|end|]
```

This marker would be placed immediately after the template type marker. So, for example, if you change the syntax such that the async marker is `async` and the loop marker is `for`, you would get something like this:

```js
[| for async item : context.getItemsAsync() |]
    [| item |]
[|end|]
```

The only possible issue would be that the bridge eval function may not support `await` and `async`, which I don't think is the case.

**Comment by pebly** [comment]
🔥

**Comment by AndrewIGD** [comment]
🔥

**Comment by UnexomWid** [comment]
Unfortunately, this isn't quite possible, due to the limitations imposed by N-API and V8. Executing async javascript code with `await` isn't possible, and even if it were, Eryn would need to retain the current state, return to the caller, and then come  back later (for example, the template content could call a function at the end, which continues the rendering process).

Another solution would be to run Eryn on a completely different native thread. However, this is impossible due to the fact that the javascript code cannot be executed on multiple threads, only the main one. Therefore, it's simply not possible to add this kind of  functionality, even if it would've been very handy.
